// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0-devel
// 	protoc        v3.15.6
// source: grpc-contract/tracker-service/v1/issue/issue.proto

package issue

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IssueByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *IssueByIdRequest) Reset() {
	*x = IssueByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_contract_tracker_service_v1_issue_issue_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IssueByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueByIdRequest) ProtoMessage() {}

func (x *IssueByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_contract_tracker_service_v1_issue_issue_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueByIdRequest.ProtoReflect.Descriptor instead.
func (*IssueByIdRequest) Descriptor() ([]byte, []int) {
	return file_grpc_contract_tracker_service_v1_issue_issue_proto_rawDescGZIP(), []int{0}
}

func (x *IssueByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type IssueResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Desc           string `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	IssueType      string `protobuf:"bytes,4,opt,name=issue_type,json=issueType,proto3" json:"issue_type,omitempty"`
	Status         string `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	BugTrace       string `protobuf:"bytes,6,opt,name=bug_trace,json=bugTrace,proto3" json:"bug_trace,omitempty"`
	User           string `protobuf:"bytes,7,opt,name=user,proto3" json:"user,omitempty"`
	Project        string `protobuf:"bytes,8,opt,name=project,proto3" json:"project,omitempty"`
	CreatedOn      int64  `protobuf:"varint,9,opt,name=created_on,json=createdOn,proto3" json:"created_on,omitempty"`
	LastModifiedOn int64  `protobuf:"varint,10,opt,name=last_modified_on,json=lastModifiedOn,proto3" json:"last_modified_on,omitempty"`
}

func (x *IssueResponse) Reset() {
	*x = IssueResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_contract_tracker_service_v1_issue_issue_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IssueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueResponse) ProtoMessage() {}

func (x *IssueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_contract_tracker_service_v1_issue_issue_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueResponse.ProtoReflect.Descriptor instead.
func (*IssueResponse) Descriptor() ([]byte, []int) {
	return file_grpc_contract_tracker_service_v1_issue_issue_proto_rawDescGZIP(), []int{1}
}

func (x *IssueResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IssueResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *IssueResponse) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *IssueResponse) GetIssueType() string {
	if x != nil {
		return x.IssueType
	}
	return ""
}

func (x *IssueResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *IssueResponse) GetBugTrace() string {
	if x != nil {
		return x.BugTrace
	}
	return ""
}

func (x *IssueResponse) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *IssueResponse) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *IssueResponse) GetCreatedOn() int64 {
	if x != nil {
		return x.CreatedOn
	}
	return 0
}

func (x *IssueResponse) GetLastModifiedOn() int64 {
	if x != nil {
		return x.LastModifiedOn
	}
	return 0
}

type IssuesByProjectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProjectId string `protobuf:"bytes,1,opt,name=projectId,proto3" json:"projectId,omitempty"`
}

func (x *IssuesByProjectRequest) Reset() {
	*x = IssuesByProjectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_contract_tracker_service_v1_issue_issue_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IssuesByProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssuesByProjectRequest) ProtoMessage() {}

func (x *IssuesByProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_contract_tracker_service_v1_issue_issue_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssuesByProjectRequest.ProtoReflect.Descriptor instead.
func (*IssuesByProjectRequest) Descriptor() ([]byte, []int) {
	return file_grpc_contract_tracker_service_v1_issue_issue_proto_rawDescGZIP(), []int{2}
}

func (x *IssuesByProjectRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type IssuesByUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *IssuesByUserRequest) Reset() {
	*x = IssuesByUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_contract_tracker_service_v1_issue_issue_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IssuesByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssuesByUserRequest) ProtoMessage() {}

func (x *IssuesByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_contract_tracker_service_v1_issue_issue_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssuesByUserRequest.ProtoReflect.Descriptor instead.
func (*IssuesByUserRequest) Descriptor() ([]byte, []int) {
	return file_grpc_contract_tracker_service_v1_issue_issue_proto_rawDescGZIP(), []int{3}
}

func (x *IssuesByUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type IssuesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Issues []*IssueResponse `protobuf:"bytes,1,rep,name=issues,proto3" json:"issues,omitempty"`
}

func (x *IssuesResponse) Reset() {
	*x = IssuesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_contract_tracker_service_v1_issue_issue_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IssuesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssuesResponse) ProtoMessage() {}

func (x *IssuesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_contract_tracker_service_v1_issue_issue_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssuesResponse.ProtoReflect.Descriptor instead.
func (*IssuesResponse) Descriptor() ([]byte, []int) {
	return file_grpc_contract_tracker_service_v1_issue_issue_proto_rawDescGZIP(), []int{4}
}

func (x *IssuesResponse) GetIssues() []*IssueResponse {
	if x != nil {
		return x.Issues
	}
	return nil
}

type CreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Issue *IssueResponse `protobuf:"bytes,1,opt,name=issue,proto3" json:"issue,omitempty"`
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_contract_tracker_service_v1_issue_issue_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_contract_tracker_service_v1_issue_issue_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_grpc_contract_tracker_service_v1_issue_issue_proto_rawDescGZIP(), []int{5}
}

func (x *CreateRequest) GetIssue() *IssueResponse {
	if x != nil {
		return x.Issue
	}
	return nil
}

type PutRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Issue *IssueResponse `protobuf:"bytes,1,opt,name=issue,proto3" json:"issue,omitempty"`
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_contract_tracker_service_v1_issue_issue_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_contract_tracker_service_v1_issue_issue_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_grpc_contract_tracker_service_v1_issue_issue_proto_rawDescGZIP(), []int{6}
}

func (x *PutRequest) GetIssue() *IssueResponse {
	if x != nil {
		return x.Issue
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_contract_tracker_service_v1_issue_issue_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_contract_tracker_service_v1_issue_issue_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_grpc_contract_tracker_service_v1_issue_issue_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GenericResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GenericResponse) Reset() {
	*x = GenericResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_contract_tracker_service_v1_issue_issue_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenericResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericResponse) ProtoMessage() {}

func (x *GenericResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_contract_tracker_service_v1_issue_issue_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericResponse.ProtoReflect.Descriptor instead.
func (*GenericResponse) Descriptor() ([]byte, []int) {
	return file_grpc_contract_tracker_service_v1_issue_issue_proto_rawDescGZIP(), []int{8}
}

var File_grpc_contract_tracker_service_v1_issue_issue_proto protoreflect.FileDescriptor

var file_grpc_contract_tracker_service_v1_issue_issue_proto_rawDesc = []byte{
	0x0a, 0x32, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2f,
	0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f,
	0x76, 0x31, 0x2f, 0x69, 0x73, 0x73, 0x75, 0x65, 0x2f, 0x69, 0x73, 0x73, 0x75, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x69, 0x73, 0x73, 0x75, 0x65, 0x22, 0x22, 0x0a, 0x10, 0x49,
	0x73, 0x73, 0x75, 0x65, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x92, 0x02, 0x0a, 0x0d, 0x49, 0x73, 0x73, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x73, 0x73,
	0x75, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69,
	0x73, 0x73, 0x75, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x1b, 0x0a, 0x09, 0x62, 0x75, 0x67, 0x5f, 0x74, 0x72, 0x61, 0x63, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x75, 0x67, 0x54, 0x72, 0x61, 0x63, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65,
	0x72, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x6f, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x4f, 0x6e, 0x12, 0x28, 0x0a, 0x10, 0x6c, 0x61,
	0x73, 0x74, 0x5f, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x64, 0x5f, 0x6f, 0x6e, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x6c, 0x61, 0x73, 0x74, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x69,
	0x65, 0x64, 0x4f, 0x6e, 0x22, 0x36, 0x0a, 0x16, 0x49, 0x73, 0x73, 0x75, 0x65, 0x73, 0x42, 0x79,
	0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x22, 0x2d, 0x0a, 0x13,
	0x49, 0x73, 0x73, 0x75, 0x65, 0x73, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x3e, 0x0a, 0x0e, 0x49,
	0x73, 0x73, 0x75, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a,
	0x06, 0x69, 0x73, 0x73, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x69, 0x73, 0x73, 0x75, 0x65, 0x2e, 0x49, 0x73, 0x73, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x52, 0x06, 0x69, 0x73, 0x73, 0x75, 0x65, 0x73, 0x22, 0x3b, 0x0a, 0x0d, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x05,
	0x69, 0x73, 0x73, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x69, 0x73,
	0x73, 0x75, 0x65, 0x2e, 0x49, 0x73, 0x73, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x52, 0x05, 0x69, 0x73, 0x73, 0x75, 0x65, 0x22, 0x38, 0x0a, 0x0a, 0x50, 0x75, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x05, 0x69, 0x73, 0x73, 0x75, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x69, 0x73, 0x73, 0x75, 0x65, 0x2e, 0x49, 0x73,
	0x73, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x05, 0x69, 0x73, 0x73,
	0x75, 0x65, 0x22, 0x1f, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x11, 0x0a, 0x0f, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x90, 0x03, 0x0a, 0x0c, 0x49, 0x73, 0x73, 0x75, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3d, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x49, 0x73,
	0x73, 0x75, 0x65, 0x42, 0x79, 0x49, 0x64, 0x12, 0x17, 0x2e, 0x69, 0x73, 0x73, 0x75, 0x65, 0x2e,
	0x49, 0x73, 0x73, 0x75, 0x65, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x14, 0x2e, 0x69, 0x73, 0x73, 0x75, 0x65, 0x2e, 0x49, 0x73, 0x73, 0x75, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x49, 0x73, 0x73,
	0x75, 0x65, 0x73, 0x42, 0x79, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x1d, 0x2e, 0x69,
	0x73, 0x73, 0x75, 0x65, 0x2e, 0x49, 0x73, 0x73, 0x75, 0x65, 0x73, 0x42, 0x79, 0x50, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x69, 0x73,
	0x73, 0x75, 0x65, 0x2e, 0x49, 0x73, 0x73, 0x75, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x44, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x49, 0x73, 0x73, 0x75, 0x65, 0x73, 0x42,
	0x79, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1a, 0x2e, 0x69, 0x73, 0x73, 0x75, 0x65, 0x2e, 0x49, 0x73,
	0x73, 0x75, 0x65, 0x73, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x15, 0x2e, 0x69, 0x73, 0x73, 0x75, 0x65, 0x2e, 0x49, 0x73, 0x73, 0x75, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x49, 0x73, 0x73, 0x75, 0x65, 0x12, 0x14, 0x2e, 0x69, 0x73, 0x73, 0x75, 0x65, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e,
	0x69, 0x73, 0x73, 0x75, 0x65, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x08, 0x50, 0x75, 0x74, 0x49, 0x73, 0x73, 0x75,
	0x65, 0x12, 0x11, 0x2e, 0x69, 0x73, 0x73, 0x75, 0x65, 0x2e, 0x50, 0x75, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x69, 0x73, 0x73, 0x75, 0x65, 0x2e, 0x47, 0x65, 0x6e,
	0x65, 0x72, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0b,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x73, 0x73, 0x75, 0x65, 0x12, 0x14, 0x2e, 0x69, 0x73,
	0x73, 0x75, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x16, 0x2e, 0x69, 0x73, 0x73, 0x75, 0x65, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x69,
	0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x40, 0x5a, 0x3e, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x50, 0x65, 0x73, 0x68, 0x6f, 0x77, 0x65, 0x2f,
	0x69, 0x73, 0x73, 0x75, 0x65, 0x2d, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x2f, 0x74, 0x72,
	0x61, 0x63, 0x6b, 0x65, 0x72, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x74, 0x72,
	0x61, 0x63, 0x6b, 0x65, 0x72, 0x2f, 0x69, 0x73, 0x73, 0x75, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_grpc_contract_tracker_service_v1_issue_issue_proto_rawDescOnce sync.Once
	file_grpc_contract_tracker_service_v1_issue_issue_proto_rawDescData = file_grpc_contract_tracker_service_v1_issue_issue_proto_rawDesc
)

func file_grpc_contract_tracker_service_v1_issue_issue_proto_rawDescGZIP() []byte {
	file_grpc_contract_tracker_service_v1_issue_issue_proto_rawDescOnce.Do(func() {
		file_grpc_contract_tracker_service_v1_issue_issue_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_contract_tracker_service_v1_issue_issue_proto_rawDescData)
	})
	return file_grpc_contract_tracker_service_v1_issue_issue_proto_rawDescData
}

var file_grpc_contract_tracker_service_v1_issue_issue_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_grpc_contract_tracker_service_v1_issue_issue_proto_goTypes = []interface{}{
	(*IssueByIdRequest)(nil),       // 0: issue.IssueByIdRequest
	(*IssueResponse)(nil),          // 1: issue.IssueResponse
	(*IssuesByProjectRequest)(nil), // 2: issue.IssuesByProjectRequest
	(*IssuesByUserRequest)(nil),    // 3: issue.IssuesByUserRequest
	(*IssuesResponse)(nil),         // 4: issue.IssuesResponse
	(*CreateRequest)(nil),          // 5: issue.CreateRequest
	(*PutRequest)(nil),             // 6: issue.PutRequest
	(*DeleteRequest)(nil),          // 7: issue.DeleteRequest
	(*GenericResponse)(nil),        // 8: issue.GenericResponse
}
var file_grpc_contract_tracker_service_v1_issue_issue_proto_depIdxs = []int32{
	1, // 0: issue.IssuesResponse.issues:type_name -> issue.IssueResponse
	1, // 1: issue.CreateRequest.issue:type_name -> issue.IssueResponse
	1, // 2: issue.PutRequest.issue:type_name -> issue.IssueResponse
	0, // 3: issue.IssueService.GetIssueById:input_type -> issue.IssueByIdRequest
	2, // 4: issue.IssueService.GetIssuesByProject:input_type -> issue.IssuesByProjectRequest
	3, // 5: issue.IssueService.GetIssuesByUser:input_type -> issue.IssuesByUserRequest
	5, // 6: issue.IssueService.CreateIssue:input_type -> issue.CreateRequest
	6, // 7: issue.IssueService.PutIssue:input_type -> issue.PutRequest
	7, // 8: issue.IssueService.DeleteIssue:input_type -> issue.DeleteRequest
	1, // 9: issue.IssueService.GetIssueById:output_type -> issue.IssueResponse
	4, // 10: issue.IssueService.GetIssuesByProject:output_type -> issue.IssuesResponse
	4, // 11: issue.IssueService.GetIssuesByUser:output_type -> issue.IssuesResponse
	8, // 12: issue.IssueService.CreateIssue:output_type -> issue.GenericResponse
	8, // 13: issue.IssueService.PutIssue:output_type -> issue.GenericResponse
	8, // 14: issue.IssueService.DeleteIssue:output_type -> issue.GenericResponse
	9, // [9:15] is the sub-list for method output_type
	3, // [3:9] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_grpc_contract_tracker_service_v1_issue_issue_proto_init() }
func file_grpc_contract_tracker_service_v1_issue_issue_proto_init() {
	if File_grpc_contract_tracker_service_v1_issue_issue_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_contract_tracker_service_v1_issue_issue_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IssueByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_contract_tracker_service_v1_issue_issue_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IssueResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_contract_tracker_service_v1_issue_issue_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IssuesByProjectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_contract_tracker_service_v1_issue_issue_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IssuesByUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_contract_tracker_service_v1_issue_issue_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IssuesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_contract_tracker_service_v1_issue_issue_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_contract_tracker_service_v1_issue_issue_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_contract_tracker_service_v1_issue_issue_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_contract_tracker_service_v1_issue_issue_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenericResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_contract_tracker_service_v1_issue_issue_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_contract_tracker_service_v1_issue_issue_proto_goTypes,
		DependencyIndexes: file_grpc_contract_tracker_service_v1_issue_issue_proto_depIdxs,
		MessageInfos:      file_grpc_contract_tracker_service_v1_issue_issue_proto_msgTypes,
	}.Build()
	File_grpc_contract_tracker_service_v1_issue_issue_proto = out.File
	file_grpc_contract_tracker_service_v1_issue_issue_proto_rawDesc = nil
	file_grpc_contract_tracker_service_v1_issue_issue_proto_goTypes = nil
	file_grpc_contract_tracker_service_v1_issue_issue_proto_depIdxs = nil
}
