version: '3'
services:
  gateway-service:
    image: pnedelev/gateway-service
    restart: unless-stopped
    ports:
      - "80:3000"
      # - "443:443"
    # environment: 
    #   MOCK_USER: nedelevbg@gmail.com
    depends_on: 
      - tracker-service

  tracker-service:
    image: pnedelev/tracker-service
    restart: unless-stopped
    environment:
      MONGO_ADDRESS: mongodb://mongo:27017
      MONGO_DB: "test-mongo"
      KAFKA_ADDRESS: kafka:9092
    # ports:
    #   - "80:4040"
      # - "443:443"
    depends_on: 
      - mongo
      - kafka

  mail-service:
    image: pnedelev/mail-service
    restart: unless-stopped
    environment:
      SMTP_ADDRESS: smtp-server
      SMTP_PORT: 25
      MONGO_ADDRESS: mongodb://mongo:27017
      MONGO_DB: "mail-service"
      KAFKA_ADDRESS: kafka:9092
    depends_on: 
      - mongo
      - kafka
      - smtp-server

  smtp-server:
    image: bytemark/smtp
    restart: unless-stopped

  mongo:
    image: mongo
    restart: unless-stopped
    # ports:
    #   - "27017:27017"
    volumes:
      - mongodata:/data/db
  
  zookeeper:
    image: wurstmeister/zookeeper

  kafka:
    image: wurstmeister/kafka
    restart: unless-stopped
    # ports:
    #   - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on: 
      - zookeeper


volumes:
  mongodata:
  # kafkadata: