// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0-devel
// 	protoc        v3.15.6
// source: grpc-contract/mail-service/v1/mailer/mailer.proto

package mailer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserPreferenceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User string `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *UserPreferenceRequest) Reset() {
	*x = UserPreferenceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_contract_mail_service_v1_mailer_mailer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserPreferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPreferenceRequest) ProtoMessage() {}

func (x *UserPreferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_contract_mail_service_v1_mailer_mailer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPreferenceRequest.ProtoReflect.Descriptor instead.
func (*UserPreferenceRequest) Descriptor() ([]byte, []int) {
	return file_grpc_contract_mail_service_v1_mailer_mailer_proto_rawDescGZIP(), []int{0}
}

func (x *UserPreferenceRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type UserPreference struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User                 string `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	IsMailNotificationOn bool   `protobuf:"varint,2,opt,name=is_mail_notification_on,json=isMailNotificationOn,proto3" json:"is_mail_notification_on,omitempty"`
}

func (x *UserPreference) Reset() {
	*x = UserPreference{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_contract_mail_service_v1_mailer_mailer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserPreference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPreference) ProtoMessage() {}

func (x *UserPreference) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_contract_mail_service_v1_mailer_mailer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPreference.ProtoReflect.Descriptor instead.
func (*UserPreference) Descriptor() ([]byte, []int) {
	return file_grpc_contract_mail_service_v1_mailer_mailer_proto_rawDescGZIP(), []int{1}
}

func (x *UserPreference) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *UserPreference) GetIsMailNotificationOn() bool {
	if x != nil {
		return x.IsMailNotificationOn
	}
	return false
}

type GenericResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GenericResponse) Reset() {
	*x = GenericResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_contract_mail_service_v1_mailer_mailer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenericResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericResponse) ProtoMessage() {}

func (x *GenericResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_contract_mail_service_v1_mailer_mailer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericResponse.ProtoReflect.Descriptor instead.
func (*GenericResponse) Descriptor() ([]byte, []int) {
	return file_grpc_contract_mail_service_v1_mailer_mailer_proto_rawDescGZIP(), []int{2}
}

var File_grpc_contract_mail_service_v1_mailer_mailer_proto protoreflect.FileDescriptor

var file_grpc_contract_mail_service_v1_mailer_mailer_proto_rawDesc = []byte{
	0x0a, 0x31, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2f,
	0x6d, 0x61, 0x69, 0x6c, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x2f,
	0x6d, 0x61, 0x69, 0x6c, 0x65, 0x72, 0x2f, 0x6d, 0x61, 0x69, 0x6c, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6d, 0x61, 0x69, 0x6c, 0x65, 0x72, 0x22, 0x2b, 0x0a, 0x15, 0x55,
	0x73, 0x65, 0x72, 0x50, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x5b, 0x0a, 0x0e, 0x55, 0x73, 0x65, 0x72,
	0x50, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x35,
	0x0a, 0x17, 0x69, 0x73, 0x5f, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x14, 0x69, 0x73, 0x4d, 0x61, 0x69, 0x6c, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x4f, 0x6e, 0x22, 0x11, 0x0a, 0x0f, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x9f, 0x01, 0x0a, 0x0b, 0x4d, 0x61, 0x69,
	0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4a, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x50, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x1d, 0x2e,
	0x6d, 0x61, 0x69, 0x6c, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x65, 0x66, 0x65,
	0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x6d,
	0x61, 0x69, 0x6c, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x65, 0x66, 0x65, 0x72,
	0x65, 0x6e, 0x63, 0x65, 0x12, 0x44, 0x0a, 0x11, 0x53, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x50,
	0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x16, 0x2e, 0x6d, 0x61, 0x69, 0x6c,
	0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63,
	0x65, 0x1a, 0x17, 0x2e, 0x6d, 0x61, 0x69, 0x6c, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x50, 0x65, 0x73, 0x68, 0x6f, 0x77, 0x65,
	0x2f, 0x69, 0x73, 0x73, 0x75, 0x65, 0x2d, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x2f, 0x6d,
	0x61, 0x69, 0x6c, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x6d, 0x61, 0x69, 0x6c,
	0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_contract_mail_service_v1_mailer_mailer_proto_rawDescOnce sync.Once
	file_grpc_contract_mail_service_v1_mailer_mailer_proto_rawDescData = file_grpc_contract_mail_service_v1_mailer_mailer_proto_rawDesc
)

func file_grpc_contract_mail_service_v1_mailer_mailer_proto_rawDescGZIP() []byte {
	file_grpc_contract_mail_service_v1_mailer_mailer_proto_rawDescOnce.Do(func() {
		file_grpc_contract_mail_service_v1_mailer_mailer_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_contract_mail_service_v1_mailer_mailer_proto_rawDescData)
	})
	return file_grpc_contract_mail_service_v1_mailer_mailer_proto_rawDescData
}

var file_grpc_contract_mail_service_v1_mailer_mailer_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_grpc_contract_mail_service_v1_mailer_mailer_proto_goTypes = []interface{}{
	(*UserPreferenceRequest)(nil), // 0: mailer.UserPreferenceRequest
	(*UserPreference)(nil),        // 1: mailer.UserPreference
	(*GenericResponse)(nil),       // 2: mailer.GenericResponse
}
var file_grpc_contract_mail_service_v1_mailer_mailer_proto_depIdxs = []int32{
	0, // 0: mailer.MailService.GetUserPreference:input_type -> mailer.UserPreferenceRequest
	1, // 1: mailer.MailService.SetUserPreference:input_type -> mailer.UserPreference
	1, // 2: mailer.MailService.GetUserPreference:output_type -> mailer.UserPreference
	2, // 3: mailer.MailService.SetUserPreference:output_type -> mailer.GenericResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_contract_mail_service_v1_mailer_mailer_proto_init() }
func file_grpc_contract_mail_service_v1_mailer_mailer_proto_init() {
	if File_grpc_contract_mail_service_v1_mailer_mailer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_contract_mail_service_v1_mailer_mailer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserPreferenceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_contract_mail_service_v1_mailer_mailer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserPreference); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_contract_mail_service_v1_mailer_mailer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenericResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_contract_mail_service_v1_mailer_mailer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_contract_mail_service_v1_mailer_mailer_proto_goTypes,
		DependencyIndexes: file_grpc_contract_mail_service_v1_mailer_mailer_proto_depIdxs,
		MessageInfos:      file_grpc_contract_mail_service_v1_mailer_mailer_proto_msgTypes,
	}.Build()
	File_grpc_contract_mail_service_v1_mailer_mailer_proto = out.File
	file_grpc_contract_mail_service_v1_mailer_mailer_proto_rawDesc = nil
	file_grpc_contract_mail_service_v1_mailer_mailer_proto_goTypes = nil
	file_grpc_contract_mail_service_v1_mailer_mailer_proto_depIdxs = nil
}
