// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package mailer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MailServiceClient is the client API for MailService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MailServiceClient interface {
	GetUserPreference(ctx context.Context, in *UserPreferenceRequest, opts ...grpc.CallOption) (*UserPreference, error)
	SetUserPreference(ctx context.Context, in *UserPreference, opts ...grpc.CallOption) (*GenericResponse, error)
}

type mailServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMailServiceClient(cc grpc.ClientConnInterface) MailServiceClient {
	return &mailServiceClient{cc}
}

func (c *mailServiceClient) GetUserPreference(ctx context.Context, in *UserPreferenceRequest, opts ...grpc.CallOption) (*UserPreference, error) {
	out := new(UserPreference)
	err := c.cc.Invoke(ctx, "/mailer.MailService/GetUserPreference", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailServiceClient) SetUserPreference(ctx context.Context, in *UserPreference, opts ...grpc.CallOption) (*GenericResponse, error) {
	out := new(GenericResponse)
	err := c.cc.Invoke(ctx, "/mailer.MailService/SetUserPreference", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MailServiceServer is the server API for MailService service.
// All implementations must embed UnimplementedMailServiceServer
// for forward compatibility
type MailServiceServer interface {
	GetUserPreference(context.Context, *UserPreferenceRequest) (*UserPreference, error)
	SetUserPreference(context.Context, *UserPreference) (*GenericResponse, error)
	mustEmbedUnimplementedMailServiceServer()
}

// UnimplementedMailServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMailServiceServer struct {
}

func (UnimplementedMailServiceServer) GetUserPreference(context.Context, *UserPreferenceRequest) (*UserPreference, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserPreference not implemented")
}
func (UnimplementedMailServiceServer) SetUserPreference(context.Context, *UserPreference) (*GenericResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetUserPreference not implemented")
}
func (UnimplementedMailServiceServer) mustEmbedUnimplementedMailServiceServer() {}

// UnsafeMailServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MailServiceServer will
// result in compilation errors.
type UnsafeMailServiceServer interface {
	mustEmbedUnimplementedMailServiceServer()
}

func RegisterMailServiceServer(s grpc.ServiceRegistrar, srv MailServiceServer) {
	s.RegisterService(&MailService_ServiceDesc, srv)
}

func _MailService_GetUserPreference_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserPreferenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailServiceServer).GetUserPreference(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mailer.MailService/GetUserPreference",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailServiceServer).GetUserPreference(ctx, req.(*UserPreferenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailService_SetUserPreference_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserPreference)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailServiceServer).SetUserPreference(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mailer.MailService/SetUserPreference",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailServiceServer).SetUserPreference(ctx, req.(*UserPreference))
	}
	return interceptor(ctx, in, info, handler)
}

// MailService_ServiceDesc is the grpc.ServiceDesc for MailService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MailService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mailer.MailService",
	HandlerType: (*MailServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserPreference",
			Handler:    _MailService_GetUserPreference_Handler,
		},
		{
			MethodName: "SetUserPreference",
			Handler:    _MailService_SetUserPreference_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc-contract/mail-service/v1/mailer.proto",
}
