apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gateway-app
  name: gateway-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-app
  strategy: {}
  template:
    metadata:
      annotations:
      labels:
        app: gateway-app
    spec:
      containers:
      - name: gateway-app
        image: pnedelev/gateway-service
        imagePullPolicy: ""
        env:
        - name: MOCK_USER
          value: nedelevbg@gmail.com
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gateway-service
  name: gateway-service
spec:
  selector:
    app: gateway-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 30000