apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka
  name: kafka-service
spec:
  selector:
    app: kafka
  ports:
    - protocol: TCP
      name: kafka-port
      port: 9092
      targetPort: 9092
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  strategy: {}
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - env:
        # - name: KAFKA_ADVERTISED_PORT
        #   value: "9092"
        # - name: KAFKA_ADVERTISED_HOST_NAME
        #   value: kafka-service
        # - name: KAFKA_BROKER_ID
        #   value: "1"
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://:9092
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka:9092
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper-service:2181
        # - name: KAFKA_CREATE_TOPICS
        #   value: "issue-channel:1:1,project-channel:1:1"
        image: wurstmeister/kafka:latest
        imagePullPolicy: ""
        name: kafka
        resources: {}
        ports:
          - containerPort: 9092
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}