apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mail-app
  name: mail-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mail-app
  strategy: {}
  template:
    metadata:
      labels:
        app: mail-app
    spec:
      containers:
      - name: mail-app
        image: pnedelev/mail-service
        imagePullPolicy: ""
        env:
        - name: KAFKA_ADDRESS
          value: kafka:9092
        - name: MONGO_ADDRESS
          value: mongodb://mongo-service:27017
        - name: MONGO_DB
          value: mail-service
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-username
        - name: MONGO_PASS
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-password
        - name: SMTP_ADDRESS
          value: smtp-service
        - name: SMTP_PORT
          value: "25"
        ports:
        - containerPort: 4040
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
--- 
apiVersion: v1
kind: Service
metadata:
  name: mail-service
spec:
  selector:
    app: mail-app
  ports:
    - protocol: TCP
      port: 4040
      targetPort: 4040
